### PR TITLE
Fix & Add

### PR DESCRIPTION
**Pull request by CrackFileso**
> Fix Attach a Small and old Mistake & Add useful stuff in old JbyeMod
> Add SomeThing in  and 

https://github.com/java-deobfuscator > SignatureFix &  AccessFixer
https://github.com/ItzSomebody/Radon/ > hasAnnotations() Check

### CODE REVIEW

**Comment by ItzSomebody** [comment]
@CrackFileso When you zero out the access flags, you don't need to check for "<" because of the nature of how a bitwise AND works.

**Comment by GraxCode** [comment]
I mean that there is no translation support in this request

**Comment by ItzSomebody** [comment]
@GraxCode I was referring to [this line](https://github.com/GraxCode/JByteMod-Beta/blob/ae224eef467a1b1fe24417b8b6191817eddb26bd/src/main/java/me/grax/jbytemod/ui/MyMenuBar.java#L429). When I said 

> ...how a bitwise AND works.

What I meant is that checking for "<" is unnecessary because the flipped bit pattern will strip out ACC_SYNTHETIC | ACC_BRIDGE via the bitwise & (AND) operator.

**Comment by CrackFileso** [comment]
ok i will add language support soon.
and thanks @ItzSomebody

**Comment by CrackFileso** [comment]
@GraxCode Language Support Finished.

**Pull request merged**
